### ISSUE TITLE
I had a very similar idea...

### ISSUE THREAD

**Issue by rozzzly** [philcockfield/react-schema#4]
So, I wrote a little library a few months ago, and have just been sitting on it. Parts of this repo, and [**[`philcockfield/ui-harness`]**](https://github.com/philcockfield/ui-harness) both brush up against what I was working on. **(They are distinct however!)** I thought I'd just share an example of what a developer consuming my library might write. I think that this could be a killer combo when mixed with @philcockfield (I'll explain why below)

So I was looking at [**[`callemall/material-ui`]**](https://github.com/callemall/material-ui), and found that it's site's documentation for the params accepted by each component... well, sucked. A lot of it was outdate. And about half of the props were undocumented (especially the styles, although that's not exactly the same...) but this got me thinking.

**What If I could explicitly define a finite set of values, an enum, that would be supported for a given prop?**

It would be trivial to pipe the structure out into some documentation generator, or better yet, a jsdoc `@typedef` block so I can get autocompletion! No more need to refer back to the docs :)

_`CommonOpts.js`_

``` javascript
const CommonOpts = new OptsObject('Common', {
    // shorthand for CommonOpts.sizes.mini, etc
    sizes: ['normal', 'mini', 'tiny', 'small', 'medium', 'large', 'big', 'huge', 'massive'],
    // ... 
    colorPallet: [
        'standard', 'red',      'orange',   'yellow',   'olive',
        'green',    'teal',     'blue',     'violet',   'purple',
        'pink',     'brown',    'grey',     'black'
    ],
    // ...
});
export default CommonOpts;
```

_`Button.js`_

``` javascript
// ...
import CommonOpts from '../../util/CommonOpts';
// ...
export const ButtonOpts = new OptsObject('Button', {
    sizes: CommonOpts.sizes, // Components can share the same possible property values, makes defining the enums much quicker
    labelPositions: CommonOpts.labelPositions,
    colors: {
        ...CommonOpts.colorPallet, // or do es6 spread to merge some generic Opts multiple components will have
        'rgba(0, 0, 0, 0.5)', //you could even add/overwrite with your own on top of the inherited Opts
    },
    flavors: [ // (visual) variations on the generic button component
        // styles
        'primary', 'secondary', 'inverted', 'positive', 'negative',
        // looks
        'circular', 'basic', 'raised',
        // layouts
        'fluid', 'compact',
        // create a facebook, twitter, or github theme button?
        { social: CommonOpts.social } // ButtonOpts.flavors.social.facebook, etc --> natural nesting
    ],
    floated: {
        ...CommonOpts.floated
    },
    // synonym for "states" --> don't want conflicts with react/alt
    mode: ['active', 'disabled', 'loading'],
    // new functionalities a button can have, changes component logic
    behaviors: ['focusable', 'animated', 'toggleable'],

    types: ['button', { link: 'a' }, 'submit', 'reset']
});

export default class Button {
    static Opts = ButtonOpts;

    constructor() {
        // ...
    }

    render() { 
        // ...
        const extraClasses = [];
        if (this.props.flavor) extraClasses.push(_.isArray(this.props.flavor) ? ...this.props.flavor : this.props.flavor); // ive got another much prettier syntax too ;p

        <button class={classNames('.Button', extraClasses) type={this.props.type} />
        // ...
    }
}
```

_`ConsumingComponent.js`_

``` javascript
// ...
render() {
    return <Button flavors={[Button.Opts.flavors.raised, Button.Opts.flavors.primary]} label={this.props.text}/>
}
// ...
```

**Comment by rozzzly** [comment]
So imagine [**[`philcockfield/ui-harness`]**](https://github.com/philcockfield/ui-harness) with each of the defined PropTypes in the left nav, and a drop down to select one of the predefined values. Another great use would be to test each of the possible prop values, hell, if you wanted to, it would be quite easy to test each possible combination!

You wouldn't want to have this for every prop on every component. I have often found it useful to just define the values I expect, but take whatever the user passes regardless. Other times, if it's something specific, like say, alignment; where only _left_, _right_, or _center_ make any sense, then this helps enforce that.

I'm not sure anyone is interested in such a thing. I'm going to get around to publishing that library as it's own npm package... eventually. However, if anyone might be interested. I would be more than happy to share some of my sauce/elaborate more.

If nobody's interested, I imagine I'll probably end up forking ui-harness and doing it myself. But that wouldn't be for quite a while. **A WYSIWYG component ~~editor~~ playground would be pretty damn cool imho.**

// ps: after writing this all out, I realize that it might be better suited to the ui-harness repo given the aim of my proposal. But as far as the acutual code is concerned, it's closer to [**[`philcockfield/react-schema/`]**](https://github.com/philcockfield/react-schema/).

well thanks for reading, I'd love to hear any feedback

**Comment by philcockfield** [comment]
Hey there @rozzzly 

This is a great idea.  In fact, the original motivation for this `react-schema` module was to wrap the PropTypes as they annoyingly didn't provide any way to introspect their values - in particular `PropTypes.oneOf([...])`.

The idea (which isn't implemented yet) was to make the API view within the UIHarness (Bottom Left) editable.  

![image](https://cloud.githubusercontent.com/assets/185555/13412903/69965cc2-dfab-11e5-9ca6-389f980e3707.png)

Simple values (Numbers, Strings, Boolean) are easy to infer, but the `OneOf` enums aren't (unless you use something like this module).  And with those being introspect-able they are particularly useful for testing out each state of the components API without having to write `it` statements that repeatedly set each value - very much in the vein of what you're describing above as a WYSIWYG playground.
